prgrms-web-devcourse-final-project/WEB6_8_HaeDokCoding_BE

build.gradle.kts, src/main/java/com/back/BackApplication.java, src/main/java/com/back/global/appConfig/AppConfig.java, src/main/java/com/back/global/appConfig/JpaAuditingConfig.java, src/main/java/com/back/global/appConfig/SwaggerConfig.java, src/main/java/com/back/global/aspect/ResponseAspect.java, src/main/java/com/back/global/controller/HomeController.java, src/main/java/com/back/global/exception/ServiceException.java, src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java, src/main/java/com/back/global/init/DevInitData.java, src/main/java/com/back/global/init/TestInitData.java, src/main/java/com/back/global/rsData/RsData.java, src/main/resources/application-dev.yml, src/main/resources/application-test.yml, src/main/resources/application.yml
- test , dev,  기본 yml 분리
- 스웨거 추가 및 8080 접속시 바로 리다이렉트 되도록 설정
- 시큐리티는 아직 설정 x
- 기타 jpa, 에러처리 등 필요한 초기 설정 추가
=> [feat] 스타터 킷 설정#1

src/main/java/com/back/domain/profile/controller/ProfileController.java, src/main/java/com/back/domain/profile/dto/ProfileResponseDto.java, src/main/java/com/back/domain/profile/service/ProfileService.java, src/main/java/com/back/domain/user/entity/User.java, src/main/java/com/back/domain/user/repository/UserRepository.java, src/main/java/com/back/domain/user/support/AbvView.java
프로필 조회 기능 구현했습니다.
<br>
close #16 
<br>
<br>
=> [feat] 프로필 조회 기능 구현 #16

src/main/java/com/back/domain/mybar/controller/MyBarController.java, src/main/java/com/back/domain/mybar/dto/MyBarItemResponseDto.java, src/main/java/com/back/domain/mybar/entity/MyBar.java, src/main/java/com/back/domain/mybar/repository/MyBarRepository.java, src/main/java/com/back/domain/mybar/service/MyBarService.java
나만의 bar(킵) 추가/재추가 기능을 구현했습니다.
<br>
close #30 
<br>
<br>
<br>
=> [feat] 나만의 bar(킵) 추가/재추가 기능 구현 #30

src/main/java/com/back/domain/user/enums/AbvLevel.java
- `AbvLevel` Enum의 L1 등급에 대한 최소(min) 기준값을 0에서 5로 변경했습니다.
<br>
close #37 
<br>
<br>
<br>
=> [refactor] AbvLevel Enum의 L1 등급 기준 및 로직 변경 #37

src/main/java/com/back/domain/post/post/controller/PostController.java, src/main/java/com/back/domain/post/post/service/PostService.java
게시글 단건 조회 구현
<br>
close #44 
<br>
<br>
<br>
=> [feat] 게시글 단건 조회 구현#44

src/main/java/com/back/domain/mybar/controller/MyBarController.java, src/main/java/com/back/domain/mybar/dto/MyBarListResponseDto.java, src/main/java/com/back/domain/mybar/repository/MyBarRepository.java, src/main/java/com/back/domain/mybar/service/MyBarService.java
나만의 bar 페이지네이션을 커서 기반으로 리팩토링했습니다.
<br>
close #49 
<br>
<br>
=> [refactor] 나만의 bar 페이지네이션을 커서 기반으로 리팩토링 #49

src/main/java/com/back/domain/post/post/controller/PostController.java, src/main/java/com/back/domain/post/post/dto/request/PostCreateRequestDto.java, src/main/java/com/back/domain/post/post/dto/request/PostUpdateRequestDto.java, src/main/java/com/back/domain/post/post/entity/Post.java, src/main/java/com/back/domain/post/post/service/PostService.java
게시글 수정 구현
<br>
close #45 
<br>
<br>
<br>
=> [feat] 게시글 수정 구현#45

src/main/java/com/back/domain/post/post/controller/PostController.java, src/main/java/com/back/domain/post/post/service/PostService.java
게시글 삭제 구현
<br>
close #46 
<br>
<br>
<br>
=> [feat] 게시글 삭제 구현#46

src/main/java/com/back/domain/post/comment/controller/CommentController.java, src/main/java/com/back/domain/post/post/controller/PostController.java, src/main/java/com/back/domain/post/post/entity/Post.java, src/main/java/com/back/domain/post/post/entity/PostLike.java, src/main/java/com/back/domain/post/post/enums/PostLikeStatus.java, src/main/java/com/back/domain/post/post/repository/PostLikeRepository.java, src/main/java/com/back/domain/post/post/service/PostService.java, src/main/java/com/back/domain/user/entity/User.java
게시글 추천 기능 구현
<br>
close #102 
<br>
<br>
<br>
=> [feat] 게시글 추천 기능 구현#102

src/main/java/com/back/domain/notification/controller/NotificationController.java, src/main/java/com/back/domain/notification/dto/NotificationSettingDto.java, src/main/java/com/back/domain/notification/dto/NotificationSettingUpdateRequestDto.java, src/main/java/com/back/domain/notification/entity/NotificationSetting.java, src/main/java/com/back/domain/notification/repository/NotificationSettingRepository.java, src/main/java/com/back/domain/notification/service/NotificationSettingService.java, src/main/java/com/back/global/jwt/refreshToken/service/RefreshTokenService.java, src/main/java/com/back/global/security/CustomOAuth2LoginSuccessHandler.java, src/main/java/com/back/global/security/SecurityConfig.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
1. 기존 '${BASE_URL}/{action}/oauth2/code/{registrationId}' 은 접두사 api 없이 redirect url 호출
app.yml
app-prod.yml
운영환경에서 site.back, front url을 오버라이드 받아 ${custom.site.backUrl}/{action}/oauth2/code/{registrationId}' 에 올바로 매핑
2. 개발 편의성을 위해 db table 설정 update -> create-drop 변경
close #106 
<br>
<br>
<br>
=> [refactor] 카카오 리다이렉트 url 매핑 수정 & 배포 설정 변경

src/main/java/com/back/domain/user/dto/UserDto.java, src/main/java/com/back/domain/user/enums/AbvLevel.java
사용하지 않는 imagePath 필드 제거
<br>
close #128 
<br>
<br>
=> [refactor] 사용하지 않는 imagePath 필드 제거

src/main/java/com/back/domain/profile/dto/ProfileResponseDto.java
신규 사용자 abvDegree 기본값 처리 로직 추가
<br>
close #131 
<br>
<br>
=> [feat] 신규 사용자 abvDegree 기본값 처리 로직 추가 #131

src/main/java/com/back/domain/post/post/dto/request/PostCreateRequestDto.java, src/main/java/com/back/domain/post/post/dto/request/PostUpdateRequestDto.java, src/main/java/com/back/domain/post/post/dto/response/PostResponseDto.java, src/main/java/com/back/domain/post/post/entity/Post.java, src/main/java/com/back/domain/post/post/service/PostService.java
게시글 영상 업로드 기능 구현
post 상에서의 기능만 구현 진행했습니다.
AWS S3 외부 저장소 설정은 나중에 해야합니다.
<br>
close #127 
<br>
<br>
<br>
=> [feat] 게시글 영상 업로드 기능 구현#127

src/main/java/com/back/domain/chatbot/controller/ChatbotController.java, src/main/java/com/back/domain/cocktail/comment/controller/CocktailCommentController.java, src/main/java/com/back/domain/cocktail/controller/CocktailController.java, src/main/java/com/back/domain/cocktail/controller/CocktailShareController.java, src/main/java/com/back/domain/mybar/controller/MyBarController.java, src/main/java/com/back/domain/myhistory/controller/MyHistoryController.java, src/main/java/com/back/domain/myhistory/service/MyHistoryService.java, src/main/java/com/back/domain/notification/controller/NotificationController.java, src/main/java/com/back/domain/notification/service/NotificationService.java, src/main/java/com/back/domain/post/comment/controller/CommentController.java, src/main/java/com/back/domain/post/post/controller/PostController.java, src/main/java/com/back/domain/profile/controller/ProfileController.java, src/main/java/com/back/global/security/CustomAuthenticationFilter.java, src/main/java/com/back/global/security/SecurityConfig.java, src/main/resources/application-prod.yml, src/test/java/com/back/domain/cocktail/controller/CocktailControllerTest.java
create drop 시 외래키 제약조건 발생 -> create 변경
close #137
<br>
<br>
<br>
=> [chore] 개발 환경 ddl-auto 설정 바꾸고 다시 테스트#137

src/test/java/com/back/domain/post/post/controller/PostControllerTest.java
PostControllerTest 구현
단위테스트로 진행했습니다.
<br>
close #165 
<br>
=> [test] PostControllerTest 구현#165

src/main/java/com/back/domain/user/entity/User.java, src/main/java/com/back/global/init/DevInitData.java
user 엔티티 리스너추가
initdata null처리
<br>
=> hotfix:오류 수정

src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
FE 및 저에게 발생하던 AWS region 설정 에러로 인한 backapplication 강제 종료 문제 해결
<br>
close #169 
<br>
<br>
<br>
=> [fix] FE에 발생한 AWS region 설정 문제 해결 #169

src/main/java/com/back/domain/cocktail/comment/dto/CocktailCommentResponseDto.java, src/main/java/com/back/domain/cocktail/controller/CocktailController.java, src/main/java/com/back/domain/cocktail/controller/CocktailShareController.java, src/main/java/com/back/global/init/DevInitData.java, src/test/java/com/back/domain/cocktail/comment/controller/CocktailCommentControllerTest.java, src/test/java/com/back/domain/cocktail/controller/CocktailControllerTest.java
칵테일, 칵테일 코맨트 테스트 케이스 추가했습니다.
close #177 
<br>
<br>
=> [test]Cocktail, CocktailComment controller testCase

src/main/java/com/back/domain/chatbot/controller/ChatbotController.java, src/main/java/com/back/domain/chatbot/dto/ChatResponseDto.java, src/main/java/com/back/domain/chatbot/enums/MessageType.java, src/main/java/com/back/domain/chatbot/repository/ChatConversationRepository.java, src/main/java/com/back/domain/chatbot/service/ChatbotService.java
FE 요청 사항
- type 정의
- greeting 중복 저장 해결
- '전체' 옵션 추가
- 최대 3개까지의 데이터 받기
<br>
close #199 
<br>
<br>
- 아직 마지막 단계 input은 넣지 못함
- 추가 작업 사항 남았음
<br>
=> [feat] 단계별 추천 추가 및 '전체' 옵션 추가 #199

src/main/java/com/back/domain/chatbot/dto/ChatRequestDto.java, src/main/java/com/back/domain/chatbot/service/ChatbotService.java
전체 옵션 작동 오류 해결
close #212 
<br>
<br>
<br>
=> [fix] 전체 옵션 오류 해결 #212

src/main/resources/application-dev.yml, src/main/resources/application.yml
프로덕션 환경에서 aws 주입 못받아서 연쇄 오류 발생해서 속성 옮김
close #225 
<br>
<br>
<br>
=> [fix] aws설정 dev -> main yml로 변경 (CICD test)

src/main/java/com/back/domain/chatbot/dto/ChatRequestDto.java, src/main/java/com/back/domain/chatbot/service/ChatbotService.java
주요 변경사항
1. ChatbotService.java:90 - 3단계 우선순위 로직
// 1순위: currentStep 명시적 제어
- currentStep == 0 → 질문형 추천
- currentStep 1~4 → 단계별 추천
- 그 외 → 에러 응답
// 2순위: 키워드 감지 (레거시)
- "단계별 추천" 키워드 감지 시 자동으로 currentStep=1 설정
// 3순위: 기본 일반 대화
2. 새로운 메서드
- ChatbotService.java:437 - generateAIResponseWithContext() - 질문형 추천 전용
- ChatbotService.java:455 - createErrorResponse() - 에러 응답 생성
3. 로깅 전략
- [EXPLICIT] - currentStep 명시적 사용
- [LEGACY] - 키워드 기반 감지 (deprecated)
- [DEFAULT] - 일반 대화 모드
4. Deprecated 처리
- ChatRequestDto.java:22 - isStepRecommendation 필드
- ChatbotService.java:427 - isStepRecommendationTrigger() 메서드
<br>
close #227 
<br>
<br>
<br>
=> [fix] chatbot 도메인 currentStep 관련 문제 해결 #227

src/main/java/com/back/domain/chatbot/dto/ChatResponseDto.java, src/main/java/com/back/domain/chatbot/service/ChatbotService.java
greeting의 DTO 응답구조, chatresponse 형식으로 통일
<br>
close #234 
<br>
<br>
<br>
=> [refactor] 챗봇 - 응답구조 통일 #234

src/main/java/com/back/domain/chatbot/dto/ChatRequestDto.java, src/main/java/com/back/domain/chatbot/enums/MessageType.java, src/main/java/com/back/domain/chatbot/service/ChatbotService.java
3단계 기존 샷잔 선택 에서 input 값 받기로 변경
<br>
close #236 
<br>
<br>
<br>
=> [feat] 챗봇 - input 추가 및 마지막 단계 삭제 #236

src/main/java/com/back/domain/post/comment/repository/CommentRepository.java, src/main/java/com/back/domain/post/comment/service/CommentService.java, src/main/java/com/back/domain/post/post/service/PostService.java
삭제된 댓글 필터링, 조회수 증가 로직 버그 수정
<br>
close #243 
<br>
<br>
<br>
=> [fix] 삭제된 댓글 필터링, 조회수 증가 로직 버그 수정#243
